---
sudo: required 

services:
  - docker

before_install:
  - docker version
  - docker info

script:
- docker build -t matthijsbos/nerdrage-platformio-remote .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push matthijsbos/nerdrage-platformio-remote:latest